drop table if exists currencies;

create table currencies (
    id int auto_increment primary key,
    code varchar(3) not null,
    currency varchar(250) not null,
    country varchar(250) not null
);

insert into currencies (code, currency, country) values ('AED', 'UAE Dirham', 'United Arab Emirates');
insert into currencies (code, currency, country) values ('AFN', 'Afghan Afghani', 'Afghanistan');
insert into currencies (code, currency, country) values ('ALL', 'Albanian Lek', 'Albania');
insert into currencies (code, currency, country) values ('AMD', 'Armenian Dram', 'Armenia');
insert into currencies (code, currency, country) values ('ANG', 'Netherlands Antillian Guilder', 'Netherlands Antilles');
insert into currencies (code, currency, country) values ('AOA', 'Angolan Kwanza', 'Angola');
insert into currencies (code, currency, country) values ('ARS', 'Argentine Peso', 'Argentina');
insert into currencies (code, currency, country) values ('AUD', 'Australian Dollar', 'Australia');
insert into currencies (code, currency, country) values ('AWG', 'Aruban Florin', 'Aruba');
insert into currencies (code, currency, country) values ('AZN', 'Azerbaijani Manat', 'Azerbaijan');
insert into currencies (code, currency, country) values ('BAM', 'Bosnia and Herzegovina Mark', 'Bosnia and Herzegovina');
insert into currencies (code, currency, country) values ('BBD', 'Barbados Dollar', 'Barbados');
insert into currencies (code, currency, country) values ('BDT', 'Bangladeshi Taka', 'Bangladesh');
insert into currencies (code, currency, country) values ('BGN', 'Bulgarian Lev', 'Bulgaria');
insert into currencies (code, currency, country) values ('BHD', 'Bahraini Dinar', 'Bahrain');
insert into currencies (code, currency, country) values ('BIF', 'Burundian Franc', 'Burundi');
insert into currencies (code, currency, country) values ('BMD', 'Bermudian Dollar', 'Bermuda');
insert into currencies (code, currency, country) values ('BND', 'Brunei Dollar', 'Brunei');
insert into currencies (code, currency, country) values ('BOB', 'Bolivian Boliviano', 'Bolivia');
insert into currencies (code, currency, country) values ('BRL', 'Brazilian Real', 'Brazil');
insert into currencies (code, currency, country) values ('BSD', 'Bahamian Dollar', 'Bahamas');
insert into currencies (code, currency, country) values ('BTN', 'Bhutanese Ngultrum', 'Bhutan');
insert into currencies (code, currency, country) values ('BWP', 'Botswana Pula', 'Botswana');
insert into currencies (code, currency, country) values ('BYN', 'Belarusian Ruble', 'Belarus');
insert into currencies (code, currency, country) values ('BZD', 'Belize Dollar', 'Belize');
insert into currencies (code, currency, country) values ('CAD', 'Canadian Dollar', 'Canada');
insert into currencies (code, currency, country) values ('CDF', 'Congolese Franc', 'Democratic Republic of the Congo');
insert into currencies (code, currency, country) values ('CHF', 'Swiss Franc', 'Switzerland');
insert into currencies (code, currency, country) values ('CLP', 'Chilean Peso', 'Chile');
insert into currencies (code, currency, country) values ('CNY', 'Chinese Renminbi', 'China');
insert into currencies (code, currency, country) values ('COP', 'Colombian Peso', 'Colombia');
insert into currencies (code, currency, country) values ('CRC', 'Costa Rican Colon', 'Costa Rica');
insert into currencies (code, currency, country) values ('CUC', 'Cuban Convertible Peso', 'Cuba');
insert into currencies (code, currency, country) values ('CUP', 'Cuban Peso', 'Cuba');
insert into currencies (code, currency, country) values ('CVE', 'Cape Verdean Escudo', 'Cape Verde');
insert into currencies (code, currency, country) values ('CZK', 'Czech Koruna', 'Czech Republic');
insert into currencies (code, currency, country) values ('DJF', 'Djiboutian Franc', 'Djibouti');
insert into currencies (code, currency, country) values ('DKK', 'Danish Krone', 'Denmark');
insert into currencies (code, currency, country) values ('DOP', 'Dominican Peso', 'Dominican Republic');
insert into currencies (code, currency, country) values ('DZD', 'Algerian Dinar', 'Algeria');
insert into currencies (code, currency, country) values ('EGP', 'Egyptian Pound', 'Egypt');
insert into currencies (code, currency, country) values ('ERN', 'Eritrean Nakfa', 'Eritrea');
insert into currencies (code, currency, country) values ('ETB', 'Ethiopian Birr', 'Ethiopia');
insert into currencies (code, currency, country) values ('EUR', 'Euro', 'European Union');
insert into currencies (code, currency, country) values ('FJD', 'Fiji Dollar', 'Fiji');
insert into currencies (code, currency, country) values ('FKP', 'Falkland Islands Pound', 'Falkland Islands');
insert into currencies (code, currency, country) values ('FOK', 'Faroese Króna', 'Faroe Islands');
insert into currencies (code, currency, country) values ('GBP', 'Pound Sterling', 'United Kingdom');
insert into currencies (code, currency, country) values ('GEL', 'Georgian Lari', 'Georgia');
insert into currencies (code, currency, country) values ('GGP', 'Guernsey Pound', 'Guernsey');
insert into currencies (code, currency, country) values ('GHS', 'Ghanaian Cedi', 'Ghana');
insert into currencies (code, currency, country) values ('GIP', 'Gibraltar Pound', 'Gibraltar');
insert into currencies (code, currency, country) values ('GMD', 'Gambian Dalasi', 'The Gambia');
insert into currencies (code, currency, country) values ('GNF', 'Guinean Franc', 'Guinea');
insert into currencies (code, currency, country) values ('GTQ', 'Guatemalan Quetzal', 'Guatemala');
insert into currencies (code, currency, country) values ('GYD', 'Guyanese Dollar', 'Guyana');
insert into currencies (code, currency, country) values ('HKD', 'Hong Kong Dollar', 'Hong Kong');
insert into currencies (code, currency, country) values ('HNL', 'Honduran Lempira', 'Honduras');
insert into currencies (code, currency, country) values ('HRK', 'Croatian Kuna', 'Croatia');
insert into currencies (code, currency, country) values ('HTG', 'Haitian Gourde', 'Haiti');
insert into currencies (code, currency, country) values ('HUF', 'Hungarian Forint', 'Hungary');
insert into currencies (code, currency, country) values ('IDR', 'Indonesian Rupiah', 'Indonesia');
insert into currencies (code, currency, country) values ('ILS', 'Israeli New Shekel', 'Israel');
insert into currencies (code, currency, country) values ('IMP', 'Manx Pound', 'Isle of Man');
insert into currencies (code, currency, country) values ('INR', 'Indian Rupee', 'India');
insert into currencies (code, currency, country) values ('IQD', 'Iraqi Dinar', 'Iraq');
insert into currencies (code, currency, country) values ('IRR', 'Iranian Rial', 'Iran');
insert into currencies (code, currency, country) values ('ISK', 'Icelandic Króna', 'Iceland');
insert into currencies (code, currency, country) values ('JMD', 'Jamaican Dollar', 'Jamaica');
insert into currencies (code, currency, country) values ('JOD', 'Jordanian Dinar', 'Jordan');
insert into currencies (code, currency, country) values ('JPY', 'Japanese Yen', 'Japan');
insert into currencies (code, currency, country) values ('KES', 'Kenyan Shilling', 'Kenya');
insert into currencies (code, currency, country) values ('KGS', 'Kyrgyzstani Som', 'Kyrgyzstan');
insert into currencies (code, currency, country) values ('KHR', 'Cambodian Riel', 'Cambodia');
insert into currencies (code, currency, country) values ('KID', 'Kiribati Dollar', 'Kiribati');
insert into currencies (code, currency, country) values ('KMF', 'Comorian Franc', 'Comoros');
insert into currencies (code, currency, country) values ('KRW', 'South Korean Won', 'South Korea');
insert into currencies (code, currency, country) values ('KWD', 'Kuwaiti Dinar', 'Kuwait');
insert into currencies (code, currency, country) values ('KYD', 'Cayman Islands Dollar', 'Cayman Islands');
insert into currencies (code, currency, country) values ('KZT', 'Kazakhstani Tenge', 'Kazakhstan');
insert into currencies (code, currency, country) values ('LAK', 'Lao Kip', 'Laos');
insert into currencies (code, currency, country) values ('LBP', 'Lebanese Pound', 'Lebanon');
insert into currencies (code, currency, country) values ('LKR', 'Sri Lanka Rupee', 'Sri Lanka');
insert into currencies (code, currency, country) values ('LRD', 'Liberian Dollar', 'Liberia');
insert into currencies (code, currency, country) values ('LSL', 'Lesotho Loti', 'Lesotho');
insert into currencies (code, currency, country) values ('LYD', 'Libyan Dinar', 'Libya');
insert into currencies (code, currency, country) values ('MAD', 'Moroccan Dirham', 'Morocco');
insert into currencies (code, currency, country) values ('MDL', 'Moldovan Leu', 'Moldova');
insert into currencies (code, currency, country) values ('MGA', 'Malagasy Ariary', 'Madagascar');
insert into currencies (code, currency, country) values ('MKD', 'Macedonian Denar', 'North Macedonia');
insert into currencies (code, currency, country) values ('MMK', 'Burmese Kyat', 'Myanmar');
insert into currencies (code, currency, country) values ('MNT', 'Mongolian Tögrög', 'Mongolia');
insert into currencies (code, currency, country) values ('MOP', 'Macanese Pataca', 'Macau');
insert into currencies (code, currency, country) values ('MRU', 'Mauritanian Ouguiya', 'Mauritania');
insert into currencies (code, currency, country) values ('MUR', 'Mauritian Rupee', 'Mauritius');
insert into currencies (code, currency, country) values ('MVR', 'Maldivian Rufiyaa', 'Maldives');
insert into currencies (code, currency, country) values ('MWK', 'Malawian Kwacha', 'Malawi');
insert into currencies (code, currency, country) values ('MXN', 'Mexican Peso', 'Mexico');
insert into currencies (code, currency, country) values ('MYR', 'Malaysian Ringgit', 'Malaysia');
insert into currencies (code, currency, country) values ('MZN', 'Mozambican Metical', 'Mozambique');
insert into currencies (code, currency, country) values ('NAD', 'Namibian Dollar', 'Namibia');
insert into currencies (code, currency, country) values ('NGN', 'Nigerian Naira', 'Nigeria');
insert into currencies (code, currency, country) values ('NIO', 'Nicaraguan Córdoba', 'Nicaragua');
insert into currencies (code, currency, country) values ('NOK', 'Norwegian Krone', 'Norway');
insert into currencies (code, currency, country) values ('NPR', 'Nepalese Rupee', 'Nepal');
insert into currencies (code, currency, country) values ('NZD', 'New Zealand Dollar', 'New Zealand');
insert into currencies (code, currency, country) values ('OMR', 'Omani Rial', 'Oman');
insert into currencies (code, currency, country) values ('PAB', 'Panamanian Balboa', 'Panama');
insert into currencies (code, currency, country) values ('PEN', 'Peruvian Sol', 'Peru');
insert into currencies (code, currency, country) values ('PGK', 'Papua New Guinean Kina', 'Papua New Guinea');
insert into currencies (code, currency, country) values ('PHP', 'Philippine Peso', 'Philippines');
insert into currencies (code, currency, country) values ('PKR', 'Pakistani Rupee', 'Pakistan');
insert into currencies (code, currency, country) values ('PLN', 'Polish Złoty', 'Poland');
insert into currencies (code, currency, country) values ('PYG', 'Paraguayan Guaraní', 'Paraguay');
insert into currencies (code, currency, country) values ('QAR', 'Qatari Riyal', 'Qatar');
insert into currencies (code, currency, country) values ('RON', 'Romanian Leu', 'Romania');
insert into currencies (code, currency, country) values ('RSD', 'Serbian Dinar', 'Serbia');
insert into currencies (code, currency, country) values ('RUB', 'Russian Ruble', 'Russia');
insert into currencies (code, currency, country) values ('RWF', 'Rwandan Franc', 'Rwanda');
insert into currencies (code, currency, country) values ('SAR', 'Saudi Riyal', 'Saudi Arabia');
insert into currencies (code, currency, country) values ('SBD', 'Solomon Islands Dollar', 'Solomon Islands');
insert into currencies (code, currency, country) values ('SCR', 'Seychellois Rupee', 'Seychelles');
insert into currencies (code, currency, country) values ('SDG', 'Sudanese Pound', 'Sudan');
insert into currencies (code, currency, country) values ('SEK', 'Swedish Krona', 'Sweden');
insert into currencies (code, currency, country) values ('SGD', 'Singapore Dollar', 'Singapore');
insert into currencies (code, currency, country) values ('SHP', 'Saint Helena Pound', 'Saint Helena');
insert into currencies (code, currency, country) values ('SLL', 'Sierra Leonean Leone', 'Sierra Leone');
insert into currencies (code, currency, country) values ('SOS', 'Somali Shilling', 'Somalia');
insert into currencies (code, currency, country) values ('SRD', 'Surinamese Dollar', 'Suriname');
insert into currencies (code, currency, country) values ('SSP', 'South Sudanese Pound', 'South Sudan');
insert into currencies (code, currency, country) values ('STN', 'São Tomé and Príncipe Dobra', 'São Tomé and Príncipe');
insert into currencies (code, currency, country) values ('SYP', 'Syrian Pound', 'Syria');
insert into currencies (code, currency, country) values ('SZL', 'Eswatini Lilangeni', 'Eswatini');
insert into currencies (code, currency, country) values ('THB', 'Thai Baht', 'Thailand');
insert into currencies (code, currency, country) values ('TJS', 'Tajikistani Somoni', 'Tajikistan');
insert into currencies (code, currency, country) values ('TMT', 'Turkmenistan Manat', 'Turkmenistan');
insert into currencies (code, currency, country) values ('TND', 'Tunisian Dinar', 'Tunisia');
insert into currencies (code, currency, country) values ('TOP', 'Tongan Paʻanga', 'Tonga');
insert into currencies (code, currency, country) values ('TRY', 'Turkish Lira', 'Turkey');
insert into currencies (code, currency, country) values ('TTD', 'Trinidad and Tobago Dollar', 'Trinidad and Tobago');
insert into currencies (code, currency, country) values ('TVD', 'Tuvaluan Dollar', 'Tuvalu');
insert into currencies (code, currency, country) values ('TWD', 'New Taiwan Dollar', 'Taiwan');
insert into currencies (code, currency, country) values ('TZS', 'Tanzanian Shilling', 'Tanzania');
insert into currencies (code, currency, country) values ('UAH', 'Ukrainian Hryvnia', 'Ukraine');
insert into currencies (code, currency, country) values ('UGX', 'Ugandan Shilling', 'Uganda');
insert into currencies (code, currency, country) values ('USD', 'United States Dollar', 'United States');
insert into currencies (code, currency, country) values ('UYU', 'Uruguayan Peso', 'Uruguay');
insert into currencies (code, currency, country) values ('UZS', 'Uzbekistani So''m', 'Uzbekistan');
insert into currencies (code, currency, country) values ('VES', 'Venezuelan Bolívar Soberano', 'Venezuela');
insert into currencies (code, currency, country) values ('VND', 'Vietnamese Đồng', 'Vietnam');
insert into currencies (code, currency, country) values ('VUV', 'Vanuatu Vatu', 'Vanuatu');
insert into currencies (code, currency, country) values ('WST', 'Samoan Tālā', 'Samoa');
insert into currencies (code, currency, country) values ('XAF', 'Central African CFA Franc', 'CEMAC');
insert into currencies (code, currency, country) values ('XCD', 'East Caribbean Dollar', 'Organisation of Eastern Caribbean States');
insert into currencies (code, currency, country) values ('XDR', 'Special Drawing Rights', 'International Monetary Fund');
insert into currencies (code, currency, country) values ('XOF', 'West African CFA franc', 'CFA');
insert into currencies (code, currency, country) values ('XPF', 'CFP Franc', 'Collectivités d''Outre-Mer');
insert into currencies (code, currency, country) values ('YER', 'Yemeni Rial', 'Yemen');
insert into currencies (code, currency, country) values ('ZAR', 'South African Rand', 'South Africa');
insert into currencies (code, currency, country) values ('ZMW', 'Zambian Kwacha', 'Zambia');

